use "$work_data/price-index.dta", clear
rename index value
generate p = "pall"
generate widcode = "inyixx999i"
// to be removed after 2020 Update
sum value if iso == "US" & year == 2018
local 2018index = r(max)
replace value = value/`2018index' if iso == "US"
tempfile priceindex
save "`priceindex'"

use "$work_data/convert-to-real-output.dta", clear
drop if (widcode == "inyixx999i") | (widcode == "icpixx999i")

append using "`priceindex'"
sort iso widcode p year



label data "Generated by add-price-index.do"
save "$work_data/add-price-index-output.dta", replace

