

// -----------------------------------------------------------------------------------------------------------------
// Russia (NPZ2017)
use "$wid_dir/Country-Updates/Russia/2017/August/russia-npz2017.dta", clear







tempfile researchers
save "`researchers'"

// ----------------------------------------------------------------------------------------------------------------
// Create metadata
generate sixlet = substr(widcode, 1, 6)
keep iso sixlet source method
order iso sixlet source method
duplicates drop
tempfile meta
save "`meta'"

// Add data to WID
use "$work_data/add-ivory-coast-data-output.dta", clear
gen oldobs=1
append using "`researchers'"
duplicates tag iso year p widcode, gen(dup)
drop if oldobs==1 & dup==1
drop oldobs dup

label data "Generated by add-researchers-data.do"
save "$work_data/add-researchers-data-output.dta", replace

// Add metadata
use "$work_data/add-ivory-coast-data-metadata.dta", clear
merge 1:1 iso sixlet using "`meta'", nogenerate update replace

label data "Generated by add-researchers-data.do"
save "$work_data/add-researchers-data-metadata.dta", replace
