use "$work_data/populations.dta", clear

tempfile popul
save "`popul'"

use "$work_data/add-national-accounts-output.dta", clear

generate newobs = 0
append using "`popul'"
replace newobs = 1 if (newobs >= .)

duplicates tag iso widcode p year, generate(duplicate)
drop if duplicate & newobs
drop duplicate newobs

label data "Generated by add-populations.do"
save "$work_data/add-populations-output.dta", replace
