use "$work_data/complete-variables-output.dta", clear

keep if inlist(substr(widcode, 1, 6), "mpweal", "mhweal", "miweal", ///
	"mgweal", "mnweal", "mnninc")
replace p="pall" if p=="p0p100"

drop currency

reshape wide value, i(iso year) j(widcode) string

foreach l in n p h i g {
	generate valuewweal`l'999i = valuem`l'weal999i/valuemnninc999i
}

keep iso year valuewweal*

reshape long value, i(iso year) j(widcode) string

drop if value >= .

generate p = "pall"

append using "$work_data/complete-variables-output.dta"

duplicates drop iso year p widcode, force

label data "Generated by calculate-wealth-income-ratios.do"
save "$work_data/calculate-wealth-income-ratio-output.dta", replace
