// -------------------------------------------------------------------------- //
// Calculate wealth-income ratios and labor/capital shares
// -------------------------------------------------------------------------- //

// -------------------------------------------------------------------------- //
// Wealth-income ratios
// -------------------------------------------------------------------------- //

use "$work_data/complete-variables-output.dta", clear

keep if inlist(substr(widcode, 1, 6), "mpweal", "mhweal", "miweal", ///
	"mgweal", "mnweal", "mnninc")
replace p="pall" if p=="p0p100"

drop currency
reshape wide value, i(iso year) j(widcode) string

foreach l in n p h i g {
	generate valuewweal`l'999i = valuem`l'weal999i/valuemnninc999i
}

keep iso year valuewweal*

reshape long value, i(iso year) j(widcode) string

drop if value >= .

generate p = "pall"

tempfile ratios
save "`ratios'"

// -------------------------------------------------------------------------- //
// Labor/capital share
// -------------------------------------------------------------------------- //

use "$work_data/complete-variables-output.dta", clear

keep if inlist(widcode, "mfkpin999i", "mnmxho999i", "mcomhn999i")
greshape wide value, i(iso year) j(widcode) string

generate valuewlabsh999i = (valuemcomhn999i + 0.7*valuemnmxho999i)/(valuemcomhn999i + valuemfkpin999i + valuemnmxho999i)
generate valuewcapsh999i = (valuemfkpin999i + 0.3*valuemnmxho999i)/(valuemcomhn999i + valuemfkpin999i + valuemnmxho999i)
keep iso year p valuew*

greshape long value, i(iso year) j(widcode) string

tempfile shares
save "`shares'"

// -------------------------------------------------------------------------- //
// Combine
// -------------------------------------------------------------------------- //

use "$work_data/complete-variables-output.dta", clear
append using "`ratios'"
append using "`shares'"

drop if missing(value)
duplicates drop iso year p widcode, force

compress
label data "Generated by calculate-wealth-income-ratios.do"
save "$work_data/calculate-wealth-income-ratio-output.dta", replace
