// Impute per-capita carbon series

use "$work_data/World-and-regional-aggregates-output.dta", clear

// Data with adult population
keep if inlist(widcode, "npopul999i")
reshape wide value, i(iso year p) j(widcode) string
keep iso year p valuenpopul999i
tempfile pop
save "`pop'"


use "$work_data/World-and-regional-aggregates-output.dta", clear
keep if substr(widcode, 1, 1) == "e"

merge n:1 iso year using "`pop'", nogenerate keep(match)

replace value = value*1e6

generate value999i = value/valuenpopul999i

keep iso year widcode p currency value999i 

reshape long value, i(iso year p widcode) j(pop) string
replace widcode = "k" + substr(widcode, 2, 5) + pop

drop pop
drop if missing(value)
/*
preserve
	use "$wid_dir/Country-Updates/Carbon/macro/April_2021/WidCarbonMetadata2.dta", clear
	rename widcode fivelet
	replace iso = "CG" if iso == "Cg"

	replace source = `"[URL][URL_LINK]https://wid.world/document/carbonmacro[/URL_LINK]"' + ///
					 `"[URL_TEXT]"' + source + `"[/URL_TEXT][/URL]"'
					 
	tempfile metacarbon
	save `metacarbon'
restore

generate fivelet = substr(widcode, 2, 5)
merge m:1 iso fivelet using "`metacarbon'", nogen keep(match)
drop fivelet
*/
append using "$wid_dir/Country-Updates/Carbon/distribution/May_2021/carbon-distribution-2021.dta"
append using "$work_data/World-and-regional-aggregates-output.dta"

*duplicates drop iso year p widcode, force

compress
label data "Generated by calculate-per-capita-carbon-series.do"
save "$work_data/calculate-per-capita-series-carbon-output.dta", replace
/*
// -----------------------------------------------------------------------------
// CREATE METADATA
// -----------------------------------------------------------------------------

// Save metadata
generate sixlet = substr(widcode, 1, 6)
keep iso sixlet source method data_quality data_points extrapolation
order iso sixlet source method

gduplicates drop iso sixlet, force

tempfile meta
save "`meta'"

use "$work_data/World-and-regional-aggregates-metadata.dta", clear
merge 1:1 iso sixlet using "`meta'", nogenerate update replace

label data "Generated by calculate-per-capita-carbon-series.do"
save "$work_data/calculate-per-capita-carbon-metadata.dta", replace
*/
