// Wealth: macroeconomic variables
import excel using "$codes_dictionary", ///
	sheet("Wealth_Macro_Variables") cellrange(D4:F149) clear allstring
keep D F
rename D widcode
rename F oldcode

replace widcode = usubinstr(widcode, "*", "m", 1)

tempfile codes
save "`codes'"

// Wealth: distributed variables
import excel using "$codes_dictionary", ///
	sheet("Wealth_Distributed_Variables") cellrange(D4:F22) clear allstring
keep D F
rename D widcode
rename F oldcode

replace widcode = usubinstr(widcode, "*", "a", 1)

append using "`codes'"
save "`codes'", replace

// Income: distributed variables
import excel using "$codes_dictionary", ///
	sheet("Income_Distributed_Variables") cellrange(D4:F98) clear allstring
keep D F
rename D widcode
rename F oldcode

replace widcode = usubinstr(widcode, "*", "a", 1)

append using "`codes'"
save "`codes'", replace

// Income: macroeconomic variables
import excel using "$codes_dictionary", ///
	sheet("Income_Macro_Variables") cellrange(D4:F137) clear allstring
keep D F
rename D widcode
rename F oldcode

replace widcode = usubinstr(widcode, "*", "m", 1)

append using "`codes'"
save "`codes'", replace

// Macro variables: other
import excel using "$codes_dictionary", ///
	sheet("Other_Macro_Variables") cellrange(D4:F17) clear allstring
keep D F
rename D widcode
rename F oldcode

replace widcode = usubinstr(widcode, "*", "m", 1)

append using "`codes'"
save "`codes'", replace

// Other WTID variables
import excel using "$codes_dictionary", ///
	sheet("Other_WTID") cellrange(A4:B123) clear allstring
rename A oldcode
rename B widcode

append using "`codes'"
save "`codes'", replace

duplicates drop
label data "Generated by import-conversion-table.do"
save "$work_data/correspondance-table.dta", replace
