tempfile fw_cpi

// Gambia
import excel "$fw_data/gambia-wages-prices-welfare-ratio.xls", ///
	clear sheet("Prices") cellrange(A4:AI88)
keep A AE AI
rename A year
rename AE cpi1
rename AI cpi2
// Average CPI
generate cpi = exp(log(cpi1)/2 + log(cpi2)/2)
generate iso = "GM"

keep iso year cpi
save "`fw_cpi'", replace

// Ghana
import excel "$fw_data/goldcoast-wages-prices-welfare-ratio.xls", ///
	clear sheet("Prices") cellrange(A4:AM84)
keep A AI AL
rename A year
rename AI cpi1
rename AL cpi2
// Average CPI
generate cpi = exp(log(cpi1)/2 + log(cpi2)/2)
generate iso = "GH"

keep iso year cpi
append using "`fw_cpi'"
save "`fw_cpi'", replace

// Kenya
import excel "$fw_data/kenya-wages-prices-welfare-ratio.xls", ///
	clear sheet("Prices") cellrange(A4:AL65)
keep A AH AK
rename A year
rename AH cpi1
rename AK cpi2
// Average CPI
generate cpi = exp(log(cpi1)/2 + log(cpi2)/2)
generate iso = "KE"

keep iso year cpi
append using "`fw_cpi'"
save "`fw_cpi'", replace

// Mauritius
import excel "$fw_data/mauritius-wages-prices-welfare-ratio.xls", ///
	clear sheet("Prices") cellrange(A4:AE82)
keep A AD
rename A year
rename AD cpi
generate iso = "MU"

keep iso year cpi
append using "`fw_cpi'"
save "`fw_cpi'", replace

// Nigeria
import excel "$fw_data/nigeria-wages-prices-welfare-ratio.xls", ///
	clear sheet("Prices") cellrange(A4:AL89)
keep A AE AH AK
rename A year
rename AE cpi1
rename AH cpi2
rename AK cpi3
// Average CPI
generate cpi = exp(log(cpi1)/3 + log(cpi2)/3 + log(cpi3)/3)

generate iso = "NG"
keep iso year cpi
append using "`fw_cpi'"
save "`fw_cpi'", replace

// Malawi + Zambia
// /!\ Note: Nyasaland correspond to the modern state of Malawi, while Zambia
//           used to be called Northern Rhodesia. However, both formed a
//           federation from 1953 to 1963. Given that there are no better
//           data available for Zambia, I use the same prices as Nyasaland.
import excel "$fw_data/nyasaland-wages-prices-welfare-ratio.xls", ///
	clear sheet("Prices") cellrange(A4:AJ68) 
keep A AF AI
rename A year
rename AF cpi

generate iso = "MW"
expand 2, generate(new)
replace iso = "ZM" if (new == 1)
keep iso year cpi
append using "`fw_cpi'"
save "`fw_cpi'", replace

// Tanzania + Zanzibar
import excel "$fw_data/tanganyika-wages-prices-welfare-ratio.xlsx", ///
	clear sheet("prices") cellrange(A4:AS48)
keep A AL AO AR
rename A year
rename AL cpi1
rename AO cpi2
rename AR cpi3
// Average CPI
generate cpi = exp(log(cpi1)/3 + log(cpi2)/3 + log(cpi3)/3)

generate iso = "TZ"
expand 2, generate(new)
replace iso = "ZZ" if (new == 1)
keep iso year cpi
append using "`fw_cpi'"
save "`fw_cpi'", replace

// Uganda
import excel "$fw_data/uganda-wages-prices-welfare-ratio.xls", ///
	clear sheet("Prices") cellrange(A4:AM63)
keep A AI AL
rename A year
rename AI cpi1
rename AL cpi2
// Average CPI
generate cpi = exp(log(cpi1)/2 + log(cpi2)/2)
generate iso = "UG"

keep iso year cpi
append using "`fw_cpi'"
save "`fw_cpi'", replace

drop if (cpi >= .) | (cpi == 0)
rename cpi cpi_fw

label data "Generated by import-fw-cpi.do"
save "$work_data/fw-cpi.dta", replace
