import excel "$input_data_dir/taxhavens-data/cpi-cbs.xlsx", firstrow clear

//	BQ cpi will be an average of the 3 municipalities
foreach var in Bonaire StEustatius Saba {
	destring `var', replace
} 

egen cpi_cbs = rowmean(Bonaire StEustatius Saba)

keep year cpi_cbs
gen iso = "BQ" 

label data "Generated by import-cbs-cpi.do"
save "$work_data/cbs-cpi.dta", replace
