use "$maddison_data/china/maddison-wu-deflator.dta", clear

rename countrycode iso
replace iso = "CN"

rename deflator def_mw
keep if def_mw < .
generate currency = "CNY"

label data "Generated by import-maddison-wu-china-deflator.do"
save "$work_data/mw-deflator.dta", replace
