import excel "$argentina_data/arklems-deflator.xlsx", clear cellrange(A46:E66)
keep A E
rename A year
rename E def_arklems
generate iso = "AR"
generate currency = "ARS"

label data "Generated by import-arklems-deflator.do"
save "$work_data/arklems-deflator.dta", replace
