// -------------------------------------------------------------------------- //
// Export countries and region codes
// -------------------------------------------------------------------------- //

import excel "$country_codes/country-codes.xlsx", clear firstrow

keep if shortname != ""
rename code iso

// -------------------------------------------------------------------------- //
// Countries only
// -------------------------------------------------------------------------- //

preserve
	drop if inrange(iso, "QB", "QZ") | iso == "WO" | iso == "XM"
	label data "Generated by import-country-codes.do"
	save "$work_data/import-country-codes-output.dta", replace
restore

// -------------------------------------------------------------------------- //
// Regions (PPP)
// -------------------------------------------------------------------------- //

preserve
	keep if inrange(iso, "QB", "QZ") | inlist(iso, "XA", "XF", "XL", "XM", "XN", "XR") | iso == "WO"
	keep iso titlename shortname
	
	generate matchname = shortname
	
	replace titlename = titlename + " (at purchasing power parity)"
	replace shortname = shortname + " (at purchasing power parity)"
	
	label data "Generated by import-country-codes.do"
	save "$work_data/import-region-codes-output.dta", replace
restore

// -------------------------------------------------------------------------- //
// Regions (MER)
// -------------------------------------------------------------------------- //

preserve
	keep if inrange(iso, "QB", "QZ") | inlist(iso, "XA", "XF", "XL", "XM", "XN", "XR") | iso == "WO"
	keep iso titlename shortname
	
	replace iso = iso + "-MER"
	replace titlename = titlename + " (at market exchange rate)"
	replace shortname = shortname + " (at market exchange rate)"
	
	label data "Generated by import-country-codes.do"
	save "$work_data/import-region-codes-mer-output.dta", replace
restore
