import delimited "$wb_data/CPI/API_FP.CPI.TOTL_DS2_en_csv_v2.csv", ///
	rowrange(3) varnames(4) clear encoding("utf8")
foreach v of varlist v5-v61 {
	local year: var label `v'
	if ("`year'" == "") {
		drop `v'
	}
	else {
		rename `v' year`year'
	}
}

drop indicatorname indicatorcode

reshape long year, i(countryname countrycode) j(j)
rename year value
rename j year

// Identify countries
countrycode countryname, generate(iso) from("wb")
drop countrycode

// Add currency from the metadata
merge n:1 countryname using "$work_data/wb-metadata.dta", ///
	keep(master match) assert(match) nogenerate keepusing(currency)
drop countryname
	
// Identify currencies
currencycode currency, generate(currency_iso) iso2c(iso) from("wb")
drop currency
rename currency_iso currency

keep if value < .
rename value cpi_wb

label data "Generated by import-wb-cpi.do"
save "$work_data/wb-cpi.dta", replace
