// The Do-file is composed of 2 parts. I am keeping the old version of the code (2011)
// So, i will not lose it and return back to it in case we want to retrieve the 2011 PPP
// The 2017 update is the second, where i make my own manipulation and modification.

//-----------------------------------------------------//

//					 The 2011 PPP        			   //

//-----------------------------------------------------//


import delimited "$oecd_data/ppp/SNA_TABLE4_20072016090738746.csv", ///
	clear encoding("utf8")

keep year country value unitcode
	
// Only keep the 2011 round
keep if year == 2011

tempfile ppp
save "`ppp'"

// Add some countries from the ICP benchmark file
import delimited "$oecd_data/ppp/PPP2011_29072016143049632.csv", ///
	clear encoding("utf8")
rename time year
keep year country value
merge 1:1 country year using "`ppp'", nogenerate update

// Identify countries
countrycode country, generate(iso) from("oecd")

// Housekeeping
keep iso unitcode year value
rename unitcode currency

rename value ppp_oecd

label data "Generated by import-ppp-oecd.do"
save "$work_data/ppp-oecd.dta", replace



//-----------------------------------------------------//

//					 The 2017 PPP Update 			   //

//-----------------------------------------------------//
/*
import delimited "$oecd_data/ppp/SNA_TABLE4_05032020140215471.csv", ///
	clear encoding("utf8")

// keep only PPPGDP and year 2017
keep if transact == "PPPGDP" & year == 2017
keep year country value unitcode
	
tempfile ppp
save "`ppp'"

// Add some countries from the ICP benchmark file
import delimited "$oecd_data/ppp/PPP2017_05032020140258689.csv", ///
	clear encoding("utf8")
keep if tab == "TAB1_12" & cat == "A0"
rename time year
keep year country value
merge 1:1 country year using "`ppp'", nogenerate update

// Identify countries
countrycode country, generate(iso) from("oecd")

// Housekeeping
keep iso unitcode year value
rename unitcode currency
replace currency = "ALL" if iso == "AL"
replace currency = "BAM" if iso == "BA"
replace currency = "EUR" if iso == "ME"
replace currency = "MKD" if iso == "MK"
replace currency = "RSD" if iso == "RS"

rename value ppp_oecd

label data "Generated by import-ppp-oecd.do"
save "$work_data/ppp-oecd.dta", replace
*/
