import excel "$input_data_dir/taxhavens-data/GDP-selected_countries.xlsx", sheet("LaneMilesiFerreti") clear firstrow

kountry IFS_Code, from(imfn) to(iso2c)
ren _ISO2C_ iso 
replace iso = "GG" if Country == "Guernsey"
replace iso = "JE" if Country == "Jersey"

ren (Country Year GDPUS Exchangerateperiodavg) (countryname year gdp_usd_lmf xrt_usd)

// GDP is in millons, getting it nominal
replace gdp_usd_lmf = gdp_usd_lmf*1000000

gen currency = ""
replace currency = "GIP" if iso == "GI"
replace currency = "JEP" if iso == "JE"
replace currency = "GGP" if iso == "GG"

drop IFS_Code

gen gdp_lcu_lmf = gdp_usd_lmf*xrt_usd

tempfile british
sa `british', replace

import excel "$input_data_dir/taxhavens-data/GDP-selected_countries.xlsx", sheet("Caribbean Netherlands") clear firstrow
ren (Country Year GDPUS) (countryname year gdp_usd_cbs)
replace iso = "BQ"

// GDP is in millons, getting it nominal
replace gdp_usd_cbs = gdp_usd_cbs*1000000

gen currency = "USD"
gen gdp_lcu_cbs = gdp_usd_cbs

append using `british'

label data "Generated by import-lmfcbs-gdp.do"
sa "$input_data_dir/taxhavens-data/GDP-selected_countries.dta", replace  
