import excel "$east_germany_data/east-germany-maddison-oecd.xlsx", ///
	clear cellrange(A3:G44)

keep A G
rename A year
rename G gdp

keep if gdp < .
replace gdp = gdp*1e6

generate iso = "DD"
generate currency = "EUR"

label data "Generated by import-maddison-east-germany-gdp.do"
save "$work_data/east-germany-gdp.dta", replace
