use "$maddison_data/china/maddison-wu-na.dta", clear

rename countrycode iso
replace iso = "CN"

rename v_gdp gdp_lcu_mw
keep if gdp_lcu_mw < .

keep iso year gdp_lcu_mw
generate currency = "CNY"
replace gdp_lcu_mw = gdp_lcu_mw*1e6

label data "Generated by import-maddison-wu-china-gdp.do"
save "$work_data/maddison-wu-gdp.dta", replace
