program currencycode, nclass
	syntax varname, generate(name) from(string) iso2c(name)
	
	quietly {
		tempvar curr
		generate `curr' = lower(strtrim(`varlist'))
		generate `generate' = ""
	
		if ("`from'" == "un sna detailed") {
			replace `generate' = "AMD" if (`iso2c' == "AM") & (`curr' == "dram")
			replace `generate' = "ANG" if (`iso2c' == "AN") & (`curr' == "netherlands antillean guilder")
			replace `generate' = "ANG" if (`iso2c' == "CW") & (`curr' == "netherlands antillean guilder")
			replace `generate' = "AOA" if (`iso2c' == "AO") & (`curr' == "(second) kwanza")
			replace `generate' = "ARS" if (`iso2c' == "AR") & (`curr' == "argentine peso")
			replace `generate' = "AUD" if (`iso2c' == "NR") & (`curr' == "australian dollar")
			replace `generate' = "AUD" if (`iso2c' == "AU") & (`curr' == "australian dollar")
			replace `generate' = "AWG" if (`iso2c' == "AW") & (`curr' == "aruban florin")
			replace `generate' = "AZN" if (`iso2c' == "AZ") & (`curr' == "azerbaijan new manat")
			replace `generate' = "BGN" if (`iso2c' == "BG") & (`curr' == "lev")
			replace `generate' = "BHD" if (`iso2c' == "BH") & (`curr' == "bahrain dinar")
			replace `generate' = "BIF" if (`iso2c' == "BI") & (`curr' == "burundi franc")
			replace `generate' = "BMD" if (`iso2c' == "BM") & (`curr' == "bermuda dollar")
			replace `generate' = "BOB" if (`iso2c' == "BO") & (`curr' == "boliviano")
			replace `generate' = "BRL" if (`iso2c' == "BR") & (`curr' == "real")
			replace `generate' = "BTN" if (`iso2c' == "BT") & (`curr' == "ngultrum")
			replace `generate' = "BWP" if (`iso2c' == "BW") & (`curr' == "pula")
			replace `generate' = "BYN" if (`iso2c' == "BY") & (`curr' == "belarussian rouble")
			replace `generate' = "BZD" if (`iso2c' == "BZ") & (`curr' == "belize dollar")
			replace `generate' = "CAD" if (`iso2c' == "CA") & (`curr' == "canadian dollar")
			replace `generate' = "CHF" if (`iso2c' == "CH") & (`curr' == "swiss franc")
			replace `generate' = "CHF" if (`iso2c' == "LI") & (`curr' == "swiss franc")
			replace `generate' = "CLP" if (`iso2c' == "CL") & (`curr' == "chilean peso")
			replace `generate' = "CNY" if (`iso2c' == "CN") & (`curr' == "yuan renminbi")
			replace `generate' = "COP" if (`iso2c' == "CO") & (`curr' == "colombian peso")
			replace `generate' = "CRC" if (`iso2c' == "CR") & (`curr' == "costa rican colon")
			replace `generate' = "CUP" if (`iso2c' == "CU") & (`curr' == "cuban peso")
			replace `generate' = "CZK" if (`iso2c' == "CZ") & (`curr' == "czech koruna")
			replace `generate' = "DKK" if (`iso2c' == "FO") & (`curr' == "danish krone")
			replace `generate' = "DKK" if (`iso2c' == "DK") & (`curr' == "danish krone")
			replace `generate' = "DKK" if (`iso2c' == "GL") & (`curr' == "danish krone")		
			replace `generate' = "DOP" if (`iso2c' == "DO") & (`curr' == "dominican peso")
			replace `generate' = "EGP" if (`iso2c' == "EG") & (`curr' == "egyptian pound")
			replace `generate' = "EUR" if (`iso2c' == "EE") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "SI") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "IE") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "SM") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "FR") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "IT") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "LT") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "SK") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "LU") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "MT") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "AT") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "BE") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "PT") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "CY") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "DE") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "ME") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "GR") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "FI") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "ES") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "LV") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "NL") & (`curr' == "euro")
			replace `generate' = "FJD" if (`iso2c' == "FJ") & (`curr' == "fiji dollar")
			replace `generate' = "GBP" if (`iso2c' == "GB") & (`curr' == "pound sterling")
			replace `generate' = "GEL" if (`iso2c' == "GE") & (`curr' == "lari")
			replace `generate' = "GNF" if (`iso2c' == "GN") & (`curr' == "guinean franc")
			replace `generate' = "GTQ" if (`iso2c' == "GT") & (`curr' == "quetzal")
			replace `generate' = "HKD" if (`iso2c' == "HK") & (`curr' == "hong kong dollar")
			replace `generate' = "HNL" if (`iso2c' == "HN") & (`curr' == "lempira")
			replace `generate' = "HRK" if (`iso2c' == "HR") & (`curr' == "kuna")
			replace `generate' = "HUF" if (`iso2c' == "HU") & (`curr' == "forint")
			replace `generate' = "ILS" if (`iso2c' == "PS") & (`curr' == "new sheqel")
			replace `generate' = "ILS" if (`iso2c' == "IL") & (`curr' == "new sheqel")
			replace `generate' = "INR" if (`iso2c' == "IN") & (`curr' == "indian rupee")
			replace `generate' = "IQD" if (`iso2c' == "IQ") & (`curr' == "iraqi dinar")
			replace `generate' = "IRR" if (`iso2c' == "IR") & (`curr' == "iranian rial")
			replace `generate' = "ISK" if (`iso2c' == "IS") & (`curr' == "icelandic króna")
			replace `generate' = "JMD" if (`iso2c' == "JM") & (`curr' == "jamaican dollar")
			replace `generate' = "JPY" if (`iso2c' == "JP") & (`curr' == "yen")
			replace `generate' = "KES" if (`iso2c' == "KE") & (`curr' == "kenya shillings")
			replace `generate' = "KGS" if (`iso2c' == "KG") & (`curr' == "kyrgyz som")
			replace `generate' = "KRW" if (`iso2c' == "KR") & (`curr' == "korean won")
			replace `generate' = "KWD" if (`iso2c' == "KW") & (`curr' == "kuwaiti dinar")
			replace `generate' = "KYD" if (`iso2c' == "KY") & (`curr' == "cayman islands dollar")
			replace `generate' = "KZT" if (`iso2c' == "KZ") & (`curr' == "tenge")
			replace `generate' = "LAK" if (`iso2c' == "LA") & (`curr' == "kip")
			replace `generate' = "LBP" if (`iso2c' == "LB") & (`curr' == "lebanese pound")
			replace `generate' = "LKR" if (`iso2c' == "LK") & (`curr' == "sri lanka rupee")
			replace `generate' = "LSL" if (`iso2c' == "LS") & (`curr' == "loti")
			replace `generate' = "MAD" if (`iso2c' == "MA") & (`curr' == "moroccan dirham")
			replace `generate' = "MDL" if (`iso2c' == "MD") & (`curr' == "moldovan leu")
			replace `generate' = "MKD" if (`iso2c' == "MK") & (`curr' == "tfyr macedonian denar")
			replace `generate' = "MNT" if (`iso2c' == "MN") & (`curr' == "togrog")
			replace `generate' = "MOP" if (`iso2c' == "MO") & (`curr' == "pataca")
			replace `generate' = "MRO" if (`iso2c' == "MR") & (`curr' == "ouguiya")
			replace `generate' = "MUR" if (`iso2c' == "MU") & (`curr' == "mauritian rupee")
			replace `generate' = "MXN" if (`iso2c' == "MX") & (`curr' == "mexican new peso")
			replace `generate' = "MYR" if (`iso2c' == "MY") & (`curr' == "ringgit")
			replace `generate' = "MZN" if (`iso2c' == "MZ") & (`curr' == "metical")
			replace `generate' = "NAD" if (`iso2c' == "NA") & (`curr' == "namibia dollar")
			replace `generate' = "NGN" if (`iso2c' == "NG") & (`curr' == "naira")
			replace `generate' = "NIO" if (`iso2c' == "NI") & (`curr' == "córdoba")
			replace `generate' = "NOK" if (`iso2c' == "NO") & (`curr' == "norwegian krone")
			replace `generate' = "NZD" if (`iso2c' == "NZ") & (`curr' == "new zealand dollar")
			replace `generate' = "PAB" if (`iso2c' == "PA") & (`curr' == "balboa")
			replace `generate' = "PEN" if (`iso2c' == "PE") & (`curr' == "new sol")
			replace `generate' = "PGK" if (`iso2c' == "PG") & (`curr' == "kina")
			replace `generate' = "PHP" if (`iso2c' == "PH") & (`curr' == "philippine peso")
			replace `generate' = "PLN" if (`iso2c' == "PL") & (`curr' == "zloty")
			replace `generate' = "PYG" if (`iso2c' == "PY") & (`curr' == "guarani")
			replace `generate' = "QAR" if (`iso2c' == "QA") & (`curr' == "qatar riyal")
			replace `generate' = "RON" if (`iso2c' == "RO") & (`curr' == "romanian leu")
			replace `generate' = "RSD" if (`iso2c' == "RS") & (`curr' == "dinar")
			replace `generate' = "RUB" if (`iso2c' == "RU") & (`curr' == "russian ruble")
			replace `generate' = "SAR" if (`iso2c' == "SA") & (`curr' == "saudi arabian riyal")
			replace `generate' = "SDG" if (`iso2c' == "SD-FORMER") & (`curr' == "sudanese pounds")
			replace `generate' = "SEK" if (`iso2c' == "SE") & (`curr' == "swedish krona")
			replace `generate' = "SLL" if (`iso2c' == "SL") & (`curr' == "leone")
			replace `generate' = "SRD" if (`iso2c' == "SR") & (`curr' == "suriname dollar")
			replace `generate' = "THB" if (`iso2c' == "TH") & (`curr' == "baht")
			replace `generate' = "TND" if (`iso2c' == "TN") & (`curr' == "tunisian dinar")
			replace `generate' = "TOP" if (`iso2c' == "TO") & (`curr' == "pa'anga")
			replace `generate' = "TRY" if (`iso2c' == "TR") & (`curr' == "new turkish lira")
			replace `generate' = "TTD" if (`iso2c' == "TT") & (`curr' == "trinidad and tobago dollar")
			replace `generate' = "TZS" if (`iso2c' == "TZ") & (`curr' == "tanzanian shilling")
			replace `generate' = "UAH" if (`iso2c' == "UA") & (`curr' == "hryvnia")
			replace `generate' = "USD" if (`iso2c' == "EC") & (`curr' == "us dollar")
			replace `generate' = "USD" if (`iso2c' == "US") & (`curr' == "us dollar")
			replace `generate' = "USD" if (`iso2c' == "PW") & (`curr' == "us dollar")
			replace `generate' = "USD" if (`iso2c' == "MH") & (`curr' == "us dollar")
			replace `generate' = "USD" if (`iso2c' == "VG") & (`curr' == "us dollar")
			replace `generate' = "USD" if (`iso2c' == "FM") & (`curr' == "us dollar")
			replace `generate' = "UYU" if (`iso2c' == "UY") & (`curr' == "uruguayan peso")
			replace `generate' = "VEF" if (`iso2c' == "VE") & (`curr' == "bolivar")
			replace `generate' = "VEF" if (`iso2c' == "VE") & (`curr' == "bolivar fuerte")
			replace `generate' = "VES" if (`iso2c' == "VE") & (`curr' == "bolivar digital")
			replace `generate' = "VND" if (`iso2c' == "VN") & (`curr' == "dong")
			replace `generate' = "VND" if (`iso2c' == "VN") & (`curr' == "vietnamese dong")
			replace `generate' = "VUV" if (`iso2c' == "VU") & (`curr' == "vatu")
			replace `generate' = "XAF" if (`iso2c' == "GA") & (`curr' == "cfa franc")
			replace `generate' = "XAF" if (`iso2c' == "CM") & (`curr' == "cfa franc")
			replace `generate' = "XCD" if (`iso2c' == "AG") & (`curr' == "ec dollar")
			replace `generate' = "XCD" if (`iso2c' == "GD") & (`curr' == "ec dollar")
			replace `generate' = "XCD" if (`iso2c' == "DM") & (`curr' == "ec dollar")
			replace `generate' = "XCD" if (`iso2c' == "MS") & (`curr' == "ec dollar")
			replace `generate' = "XCD" if (`iso2c' == "VC") & (`curr' == "ec dollar")
			replace `generate' = "XCD" if (`iso2c' == "KN") & (`curr' == "ec dollar")
			replace `generate' = "XCD" if (`iso2c' == "AI") & (`curr' == "ec dollar")
			replace `generate' = "XOF" if (`iso2c' == "SN") & (`curr' == "cfa franc")
			replace `generate' = "XOF" if (`iso2c' == "BF") & (`curr' == "cfa franc")
			replace `generate' = "XOF" if (`iso2c' == "NE") & (`curr' == "cfa franc")
			replace `generate' = "XOF" if (`iso2c' == "CI") & (`curr' == "cfa franc")
			replace `generate' = "XOF" if (`iso2c' == "TD") & (`curr' == "cfa franc")
			replace `generate' = "YER" if (`iso2c' == "YE") & (`curr' == "yemeni rial")
			replace `generate' = "ZAR" if (`iso2c' == "ZA") & (`curr' == "rand")
			replace `generate' = "MWK" if (`iso2c' == "MW") & (`curr' == "malawi kwacha")
			replace `generate' = "TJS" if (`iso2c' == "TJ") & (`curr' == "somoni")
			replace `generate' = "UGX" if (`iso2c' == "UG") & (`curr' == "uganda shilling")
			replace `generate' = "CVE" if (`iso2c' == "CV") & (`curr' == "escudo")
			replace `generate' = "ZMW" if (`iso2c' == "ZM") & (`curr' == "zambian kwacha")
		}
		else if ("`from'" == "un sna main") {
			replace `generate' = "AED" if (`iso2c' == "AE") & (`curr' == "uae dirham")
			replace `generate' = "AFN" if (`iso2c' == "AF") & (`curr' == "afghani")
			replace `generate' = "ALL" if (`iso2c' == "AL") & (`curr' == "lek")
			replace `generate' = "AMD" if (`iso2c' == "AM") & (`curr' == "armenian dram")
			replace `generate' = "ANG" if (`iso2c' == "SX") & (`curr' == "netherlands antillian guilder")
			replace `generate' = "ANG" if (`iso2c' == "CW") & (`curr' == "netherlands antillian guilder")
			replace `generate' = "ANG" if (`iso2c' == "AN") & (`curr' == "netherlands antillian guilder")
			replace `generate' = "AOA" if (`iso2c' == "AO") & (`curr' == "kwanza")
			replace `generate' = "ARS" if (`iso2c' == "AR") & (`curr' == "argentine peso")
			replace `generate' = "AUD" if (`iso2c' == "TV") & (`curr' == "australian dollar")
			replace `generate' = "AUD" if (`iso2c' == "KI") & (`curr' == "australian dollar")
			replace `generate' = "AUD" if (`iso2c' == "AU") & (`curr' == "australian dollar")
			replace `generate' = "AUD" if (`iso2c' == "NR") & (`curr' == "australian dollar")
			replace `generate' = "AWG" if (`iso2c' == "AW") & (`curr' == "aruban guilder")
			replace `generate' = "AZN" if (`iso2c' == "AZ") & (`curr' == "azerbaijanian manat")
			replace `generate' = "BAM" if (`iso2c' == "BA") & (`curr' == "convertible marks")
			replace `generate' = "BBD" if (`iso2c' == "BB") & (`curr' == "barbados dollar")
			replace `generate' = "BDT" if (`iso2c' == "BD") & (`curr' == "taka")
			replace `generate' = "BGN" if (`iso2c' == "BG") & (`curr' == "bulgarian lev")
			replace `generate' = "BHD" if (`iso2c' == "BH") & (`curr' == "bahraini dinar")
			replace `generate' = "BIF" if (`iso2c' == "BI") & (`curr' == "burundi franc")
			replace `generate' = "BMD" if (`iso2c' == "BM") & (`curr' == "bermudian dollar")
			replace `generate' = "BND" if (`iso2c' == "BN") & (`curr' == "brunei dollar")
			replace `generate' = "BOB" if (`iso2c' == "BO") & (`curr' == "boliviano")
			replace `generate' = "BRL" if (`iso2c' == "BR") & (`curr' == "brazilian real")
			replace `generate' = "BSD" if (`iso2c' == "BS") & (`curr' == "bahamian dollar")
			replace `generate' = "BTN" if (`iso2c' == "BT") & (`curr' == "ngultrum")
			replace `generate' = "BWP" if (`iso2c' == "BW") & (`curr' == "pula")
			replace `generate' = "BYN" if (`iso2c' == "BY") & (`curr' == "belarussian ruble")
			replace `generate' = "BZD" if (`iso2c' == "BZ") & (`curr' == "belize dollar")
			replace `generate' = "CAD" if (`iso2c' == "CA") & (`curr' == "canadian dollar")
			replace `generate' = "CDF" if (`iso2c' == "CD") & (`curr' == "franc congolais")
			replace `generate' = "CHF" if (`iso2c' == "LI") & (`curr' == "swiss franc")
			replace `generate' = "CHF" if (`iso2c' == "CH") & (`curr' == "swiss franc")
			replace `generate' = "CLP" if (`iso2c' == "CL") & (`curr' == "chilean peso")
			replace `generate' = "CNY" if (`iso2c' == "CN") & (`curr' == "yuan renminbi")
			replace `generate' = "COP" if (`iso2c' == "CO") & (`curr' == "colombian peso")
			replace `generate' = "CRC" if (`iso2c' == "CR") & (`curr' == "costa rican colon")
			replace `generate' = "CSK" if (`iso2c' == "CS") & (`curr' == "koruna")
			replace `generate' = "CUP" if (`iso2c' == "CU") & (`curr' == "cuban peso")
			replace `generate' = "CVE" if (`iso2c' == "CV") & (`curr' == "cabo verde escudo")
			replace `generate' = "CZK" if (`iso2c' == "CZ") & (`curr' == "czech koruna")
			replace `generate' = "DJF" if (`iso2c' == "DJ") & (`curr' == "djibouti franc")
			replace `generate' = "DKK" if (`iso2c' == "GL") & (`curr' == "danish krone")
			replace `generate' = "DKK" if (`iso2c' == "DK") & (`curr' == "danish krone")
			replace `generate' = "DOP" if (`iso2c' == "DO") & (`curr' == "dominican peso")
			replace `generate' = "DZD" if (`iso2c' == "DZ") & (`curr' == "algerian dinar")
			replace `generate' = "EGP" if (`iso2c' == "EG") & (`curr' == "egyptian pound")
			replace `generate' = "ERN" if (`iso2c' == "ER") & (`curr' == "nakfa")
			replace `generate' = "ETB" if (`iso2c' == "ET") & (`curr' == "ethiopian birr")
			replace `generate' = "ETB" if (`iso2c' == "ET-FORMER") & (`curr' == "birr")
			replace `generate' = "EUR" if (`iso2c' == "MT") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "IE") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "IT") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "PT") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "ES") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "CY") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "ME") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "KS") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "SI") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "LV") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "MC") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "AD") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "EE") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "FI") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "SM") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "LU") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "SK") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "LT") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "NL") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "AT") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "FR") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "BE") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "DE") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "GR") & (`curr' == "euro")
			replace `generate' = "FJD" if (`iso2c' == "FJ") & (`curr' == "fiji dollar")
			replace `generate' = "GBP" if (`iso2c' == "GB") & (`curr' == "pound sterling")
			replace `generate' = "GEL" if (`iso2c' == "GE") & (`curr' == "lari")
			replace `generate' = "GHS" if (`iso2c' == "GH") & (`curr' == "cedi")
			replace `generate' = "GMD" if (`iso2c' == "GM") & (`curr' == "dalasi")
			replace `generate' = "GNF" if (`iso2c' == "GN") & (`curr' == "guinea franc")
			replace `generate' = "GTQ" if (`iso2c' == "GT") & (`curr' == "quetzal")
			replace `generate' = "GYD" if (`iso2c' == "GY") & (`curr' == "guyana dollar")
			replace `generate' = "HKD" if (`iso2c' == "HK") & (`curr' == "hong kong dollar")
			replace `generate' = "HNL" if (`iso2c' == "HN") & (`curr' == "lempira")
			replace `generate' = "HRK" if (`iso2c' == "HR") & (`curr' == "croatian kuna")
			replace `generate' = "HTG" if (`iso2c' == "HT") & (`curr' == "gourde")
			replace `generate' = "HUF" if (`iso2c' == "HU") & (`curr' == "forint")
			replace `generate' = "IDR" if (`iso2c' == "ID") & (`curr' == "rupiah")
			replace `generate' = "ILS" if (`iso2c' == "IL") & (`curr' == "new israeli sheqel")
			replace `generate' = "ILS" if (`iso2c' == "PS") & (`curr' == "new israeli sheqel")
			replace `generate' = "INR" if (`iso2c' == "IN") & (`curr' == "indian rupee")
			replace `generate' = "IQD" if (`iso2c' == "IQ") & (`curr' == "iraqi dinar")
			replace `generate' = "IRR" if (`iso2c' == "IR") & (`curr' == "iranian rial")
			replace `generate' = "ISK" if (`iso2c' == "IS") & (`curr' == "iceland krona")
			replace `generate' = "JMD" if (`iso2c' == "JM") & (`curr' == "jamaican dollar")
			replace `generate' = "JOD" if (`iso2c' == "JO") & (`curr' == "jordanian dinar")
			replace `generate' = "JPY" if (`iso2c' == "JP") & (`curr' == "yen")
			replace `generate' = "KES" if (`iso2c' == "KE") & (`curr' == "kenyan shilling")
			replace `generate' = "KGS" if (`iso2c' == "KG") & (`curr' == "som")
			replace `generate' = "KHR" if (`iso2c' == "KH") & (`curr' == "riel")
			replace `generate' = "KMF" if (`iso2c' == "KM") & (`curr' == "comoro franc")
			replace `generate' = "KPW" if (`iso2c' == "KP") & (`curr' == "north korean won")
			replace `generate' = "KRW" if (`iso2c' == "KR") & (`curr' == "won")
			replace `generate' = "KWD" if (`iso2c' == "KW") & (`curr' == "kuwaiti dinar")
			replace `generate' = "KYD" if (`iso2c' == "KY") & (`curr' == "cayman islands dollar")
			replace `generate' = "KZT" if (`iso2c' == "KZ") & (`curr' == "tenge")
			replace `generate' = "LAK" if (`iso2c' == "LA") & (`curr' == "kip")
			replace `generate' = "LBP" if (`iso2c' == "LB") & (`curr' == "lebanese pound")
			replace `generate' = "LKR" if (`iso2c' == "LK") & (`curr' == "sri lanka rupee")
			replace `generate' = "LSL" if (`iso2c' == "LS") & (`curr' == "loti")
			replace `generate' = "LYD" if (`iso2c' == "LY") & (`curr' == "libyan dinar")
			replace `generate' = "MAD" if (`iso2c' == "MA") & (`curr' == "moroccan dirham")
			replace `generate' = "MDL" if (`iso2c' == "MD") & (`curr' == "moldovan leu")
			replace `generate' = "MGA" if (`iso2c' == "MG") & (`curr' == "malagasy ariary")
			replace `generate' = "MKD" if (`iso2c' == "MK") & (`curr' == "denar")
			replace `generate' = "MMK" if (`iso2c' == "MM") & (`curr' == "kyat")
			replace `generate' = "MNT" if (`iso2c' == "MN") & (`curr' == "tugrik")
			replace `generate' = "MOP" if (`iso2c' == "MO") & (`curr' == "pataca")
			replace `generate' = "MRO" if (`iso2c' == "MR") & (`curr' == "ouguiya")
			replace `generate' = "MUR" if (`iso2c' == "MU") & (`curr' == "mauritius rupee")
			replace `generate' = "MVR" if (`iso2c' == "MV") & (`curr' == "rufiyaa")
			replace `generate' = "MWK" if (`iso2c' == "MW") & (`curr' == "kwacha")
			replace `generate' = "MXN" if (`iso2c' == "MX") & (`curr' == "mexican peso")
			replace `generate' = "MYR" if (`iso2c' == "MY") & (`curr' == "malaysian ringgit")
			replace `generate' = "MZN" if (`iso2c' == "MZ") & (`curr' == "metical")
			replace `generate' = "NAD" if (`iso2c' == "NA") & (`curr' == "namibian dollar")
			replace `generate' = "NGN" if (`iso2c' == "NG") & (`curr' == "naira")
			replace `generate' = "NIO" if (`iso2c' == "NI") & (`curr' == "cordoba oro")
			replace `generate' = "NOK" if (`iso2c' == "NO") & (`curr' == "norwegian krone")
			replace `generate' = "NPR" if (`iso2c' == "NP") & (`curr' == "nepalese rupee")
			replace `generate' = "NZD" if (`iso2c' == "CK") & (`curr' == "new zealand dollar")
			replace `generate' = "NZD" if (`iso2c' == "NZ") & (`curr' == "new zealand dollar")
			replace `generate' = "OMR" if (`iso2c' == "OM") & (`curr' == "rial omani")
			replace `generate' = "OMR" if (`iso2c' == "OM") & (`curr' == "omani rial")
			replace `generate' = "PAB" if (`iso2c' == "PA") & (`curr' == "balboa")
			replace `generate' = "PEN" if (`iso2c' == "PE") & (`curr' == "nuevo sol")
			replace `generate' = "PGK" if (`iso2c' == "PG") & (`curr' == "kina")
			replace `generate' = "PHP" if (`iso2c' == "PH") & (`curr' == "philippine peso")
			replace `generate' = "PKR" if (`iso2c' == "PK") & (`curr' == "pakistan rupee")
			replace `generate' = "PLN" if (`iso2c' == "PL") & (`curr' == "zloty")
			replace `generate' = "PYG" if (`iso2c' == "PY") & (`curr' == "guarani")
			replace `generate' = "QAR" if (`iso2c' == "QA") & (`curr' == "qatari rial")
			replace `generate' = "RON" if (`iso2c' == "RO") & (`curr' == "new leu")
			replace `generate' = "RSD" if (`iso2c' == "RS") & (`curr' == "serbian dinar")
			replace `generate' = "RUB" if (`iso2c' == "RU") & (`curr' == "russian ruble")
			replace `generate' = "RWF" if (`iso2c' == "RW") & (`curr' == "rwanda franc")
			replace `generate' = "SAR" if (`iso2c' == "SA") & (`curr' == "saudi riyal")
			replace `generate' = "SBD" if (`iso2c' == "SB") & (`curr' == "solomon islands dollar")
			replace `generate' = "SCR" if (`iso2c' == "SC") & (`curr' == "seychelles rupee")
			replace `generate' = "SDG" if (`iso2c' == "SD") & (`curr' == "sudanese pound")
			replace `generate' = "SDG" if (`iso2c' == "SD-FORMER") & (`curr' == "sudanese pound")
			replace `generate' = "SEK" if (`iso2c' == "SE") & (`curr' == "swedish krona")
			replace `generate' = "SGD" if (`iso2c' == "SG") & (`curr' == "singapore dollar")
			replace `generate' = "SLL" if (`iso2c' == "SL") & (`curr' == "leone")
			replace `generate' = "SOS" if (`iso2c' == "SO") & (`curr' == "somali shilling")
			replace `generate' = "SRD" if (`iso2c' == "SR") & (`curr' == "surinam dollar")
			replace `generate' = "SSP" if (`iso2c' == "SS") & (`curr' == "south sudanese pound")
			replace `generate' = "STN" if (`iso2c' == "ST") & (`curr' == "dobra")
			replace `generate' = "SUR" if (`iso2c' == "SU") & (`curr' == "ruble")
			replace `generate' = "SYP" if (`iso2c' == "SY") & (`curr' == "syrian pound")
			replace `generate' = "SZL" if (`iso2c' == "SZ") & (`curr' == "lilangeni")
			replace `generate' = "THB" if (`iso2c' == "TH") & (`curr' == "baht")
			replace `generate' = "TJS" if (`iso2c' == "TJ") & (`curr' == "somoni")
			replace `generate' = "TMT" if (`iso2c' == "TM") & (`curr' == "turkmenistan manat")
			replace `generate' = "TND" if (`iso2c' == "TN") & (`curr' == "tunisian dinar")
			replace `generate' = "TOP" if (`iso2c' == "TO") & (`curr' == "pa'anga")
			replace `generate' = "TRY" if (`iso2c' == "TR") & (`curr' == "new turkish lira")
			replace `generate' = "TTD" if (`iso2c' == "TT") & (`curr' == "trinidad and tobago dollar")
			replace `generate' = "TZS" if (`iso2c' == "TZ") & (`curr' == "tanzanian shilling")
			replace `generate' = "TZS" if (`iso2c' == "ZZ") & (`curr' == "tanzanian shilling")
			replace `generate' = "UAH" if (`iso2c' == "UA") & (`curr' == "hryvnia")
			replace `generate' = "UGX" if (`iso2c' == "UG") & (`curr' == "uganda shilling")
			replace `generate' = "USD" if (`iso2c' == "TL") & (`curr' == "us dollar")
			replace `generate' = "USD" if (`iso2c' == "PW") & (`curr' == "us dollar")
			replace `generate' = "USD" if (`iso2c' == "VG") & (`curr' == "us dollar")
			replace `generate' = "USD" if (`iso2c' == "PR") & (`curr' == "us dollar")
			replace `generate' = "USD" if (`iso2c' == "ZW") & (`curr' == "us dollar")
			replace `generate' = "ZWD" if (`iso2c' == "ZW") & (`curr' == "zimbabwean dollar")
			replace `generate' = "USD" if (`iso2c' == "EC") & (`curr' == "us dollar")
			replace `generate' = "USD" if (`iso2c' == "FM") & (`curr' == "us dollar")
			replace `generate' = "USD" if (`iso2c' == "TC") & (`curr' == "us dollar")
			replace `generate' = "USD" if (`iso2c' == "SV") & (`curr' == "us dollar")
			replace `generate' = "USD" if (`iso2c' == "MH") & (`curr' == "us dollar")
			replace `generate' = "USD" if (`iso2c' == "LR") & (`curr' == "us dollar")
			replace `generate' = "USD" if (`iso2c' == "US") & (`curr' == "us dollar")
			replace `generate' = "UYU" if (`iso2c' == "UY") & (`curr' == "peso uruguayo")
			replace `generate' = "UZS" if (`iso2c' == "UZ") & (`curr' == "uzbekistan sum")
			replace `generate' = "UZS" if (`iso2c' == "UZ") & (`curr' == "uzbek som")
			replace `generate' = "VEF" if (`iso2c' == "VE") & (`curr' == "bolivar fuerte")
			replace `generate' = "VES" if (`iso2c' == "VE") & (`curr' == "bolivar digital")			
			replace `generate' = "VND" if (`iso2c' == "VN") & (`curr' == "dong")
			replace `generate' = "VND" if (`iso2c' == "VN") & (`curr' == "vietnamese dong")
			replace `generate' = "VUV" if (`iso2c' == "VU") & (`curr' == "vatu")
			replace `generate' = "WST" if (`iso2c' == "WS") & (`curr' == "tala")
			replace `generate' = "XAF" if (`iso2c' == "CM") & (`curr' == "cfa franc beac")
			replace `generate' = "XAF" if (`iso2c' == "GA") & (`curr' == "cfa franc beac")
			replace `generate' = "XAF" if (`iso2c' == "CG") & (`curr' == "cfa franc beac")
			replace `generate' = "XAF" if (`iso2c' == "TD") & (`curr' == "cfa franc beac")
			replace `generate' = "XAF" if (`iso2c' == "GQ") & (`curr' == "cfa franc beac")
			replace `generate' = "XAF" if (`iso2c' == "CF") & (`curr' == "cfa franc beac")
			replace `generate' = "XCD" if (`iso2c' == "AI") & (`curr' == "east caribbean dollar")
			replace `generate' = "XCD" if (`iso2c' == "KN") & (`curr' == "east caribbean dollar")
			replace `generate' = "XCD" if (`iso2c' == "VC") & (`curr' == "east caribbean dollar")
			replace `generate' = "XCD" if (`iso2c' == "LC") & (`curr' == "east caribbean dollar")
			replace `generate' = "XCD" if (`iso2c' == "GD") & (`curr' == "east caribbean dollar")
			replace `generate' = "XCD" if (`iso2c' == "AG") & (`curr' == "east caribbean dollar")
			replace `generate' = "XCD" if (`iso2c' == "MS") & (`curr' == "east caribbean dollar")
			replace `generate' = "XCD" if (`iso2c' == "DM") & (`curr' == "east caribbean dollar")
			replace `generate' = "XOF" if (`iso2c' == "ML") & (`curr' == "cfa franc bceao")
			replace `generate' = "XOF" if (`iso2c' == "BJ") & (`curr' == "cfa franc bceao")
			replace `generate' = "XOF" if (`iso2c' == "CI") & (`curr' == "cfa franc bceao")
			replace `generate' = "XOF" if (`iso2c' == "BF") & (`curr' == "cfa franc bceao")
			replace `generate' = "XOF" if (`iso2c' == "GW") & (`curr' == "cfa franc bceao")
			replace `generate' = "XOF" if (`iso2c' == "SN") & (`curr' == "cfa franc bceao")
			replace `generate' = "XOF" if (`iso2c' == "TG") & (`curr' == "cfa franc bceao")
			replace `generate' = "XOF" if (`iso2c' == "NE") & (`curr' == "cfa franc bceao")
			replace `generate' = "XPF" if (`iso2c' == "NC") & (`curr' == "cfp franc")
			replace `generate' = "XPF" if (`iso2c' == "PF") & (`curr' == "cfp franc")
			replace `generate' = "YDD" if (`iso2c' == "YD") & (`curr' == "dinar")
			replace `generate' = "YER" if (`iso2c' == "YA") & (`curr' == "rial")
			replace `generate' = "YER" if (`iso2c' == "YE") & (`curr' == "yemeni rial")
			replace `generate' = "YUN" if (`iso2c' == "YU") & (`curr' == "dinar")
			replace `generate' = "ZAR" if (`iso2c' == "ZA") & (`curr' == "rand")
			replace `generate' = "ZMW" if (`iso2c' == "ZM") & (`curr' == "kwacha")
		}
		else if ("`from'" == "wb") {
			replace `generate' = "AED" if (`iso2c' == "AE") & (`curr' == "u.a.e. dirham")
			replace `generate' = "AFN" if (`iso2c' == "AF") & (`curr' == "afghan afghani")
			replace `generate' = "ALL" if (`iso2c' == "AL") & (`curr' == "albanian lek")
			replace `generate' = "AMD" if (`iso2c' == "AM") & (`curr' == "armenian dram")
			replace `generate' = "ANG" if (`iso2c' == "SX") & (`curr' == "netherlands antillean guilder")
			replace `generate' = "ANG" if (`iso2c' == "CW") & (`curr' == "netherlands antillean guilder")
			replace `generate' = "AOA" if (`iso2c' == "AO") & (`curr' == "angolan kwanza")
			replace `generate' = "ARS" if (`iso2c' == "AR") & (`curr' == "argentine peso")
			replace `generate' = "AUD" if (`iso2c' == "AU") & (`curr' == "australian dollar")
			replace `generate' = "AUD" if (`iso2c' == "TV") & (`curr' == "australian dollar")
			replace `generate' = "AUD" if (`iso2c' == "KI") & (`curr' == "australian dollar")
			replace `generate' = "AUD" if (`iso2c' == "NR") & (`curr' == "australian dollar")
			replace `generate' = "AWG" if (`iso2c' == "AW") & (`curr' == "aruban florin")
			replace `generate' = "AZN" if (`iso2c' == "AZ") & (`curr' == "new azeri manat")
			replace `generate' = "BAM" if (`iso2c' == "BA") & (`curr' == "bosnia and herzegovina convertible mark")
			replace `generate' = "BBD" if (`iso2c' == "BB") & (`curr' == "barbados dollar")
			replace `generate' = "BDT" if (`iso2c' == "BD") & (`curr' == "bangladeshi taka")
			replace `generate' = "BGN" if (`iso2c' == "BG") & (`curr' == "bulgarian lev")
			replace `generate' = "BHD" if (`iso2c' == "BH") & (`curr' == "bahraini dinar")
			replace `generate' = "BIF" if (`iso2c' == "BI") & (`curr' == "burundi franc")
			replace `generate' = "BMD" if (`iso2c' == "BM") & (`curr' == "bermuda dollar")
			replace `generate' = "BND" if (`iso2c' == "BN") & (`curr' == "brunei dollar")
			replace `generate' = "BOB" if (`iso2c' == "BO") & (`curr' == "bolivian boliviano")
			replace `generate' = "BRL" if (`iso2c' == "BR") & (`curr' == "brazilian real")
			replace `generate' = "BSD" if (`iso2c' == "BS") & (`curr' == "bahamian dollar")
			replace `generate' = "BTN" if (`iso2c' == "BT") & (`curr' == "bhutanese ngultrum")
			replace `generate' = "BWP" if (`iso2c' == "BW") & (`curr' == "botswana pula")
			replace `generate' = "BYN" if (`iso2c' == "BY") & (`curr' == "belarusian rubel")
			replace `generate' = "BZD" if (`iso2c' == "BZ") & (`curr' == "belize dollar")
			replace `generate' = "CAD" if (`iso2c' == "CA") & (`curr' == "canadian dollar")
			replace `generate' = "CDF" if (`iso2c' == "CD") & (`curr' == "congolese franc")
			replace `generate' = "CHF" if (`iso2c' == "CH") & (`curr' == "swiss franc")
			replace `generate' = "CHF" if (`iso2c' == "LI") & (`curr' == "swiss franc")
			replace `generate' = "CLP" if (`iso2c' == "CL") & (`curr' == "chilean peso")
			replace `generate' = "CNY" if (`iso2c' == "CN") & (`curr' == "chinese yuan")
			replace `generate' = "COP" if (`iso2c' == "CO") & (`curr' == "colombian peso")
			replace `generate' = "CRC" if (`iso2c' == "CR") & (`curr' == "costa rican colon")
			replace `generate' = "CUP" if (`iso2c' == "CU") & (`curr' == "cuban peso")
			replace `generate' = "CVE" if (`iso2c' == "CV") & (`curr' == "cabo verde escudo")
			replace `generate' = "CZK" if (`iso2c' == "CZ") & (`curr' == "czech koruna")
			replace `generate' = "DJF" if (`iso2c' == "DJ") & (`curr' == "djibouti franc")
			replace `generate' = "DKK" if (`iso2c' == "DK") & (`curr' == "danish krone")
			replace `generate' = "DKK" if (`iso2c' == "GL") & (`curr' == "danish krone")
			replace `generate' = "DKK" if (`iso2c' == "FO") & (`curr' == "danish krone")
			replace `generate' = "DOP" if (`iso2c' == "DO") & (`curr' == "dominican peso")
			replace `generate' = "DZD" if (`iso2c' == "DZ") & (`curr' == "algerian dinar")
			replace `generate' = "EGP" if (`iso2c' == "EG") & (`curr' == "egyptian pound")
			replace `generate' = "ERN" if (`iso2c' == "ER") & (`curr' == "eritrean nakfa")
			replace `generate' = "ETB" if (`iso2c' == "ET") & (`curr' == "ethiopian birr")
			replace `generate' = "EUR" if (`iso2c' == "LU") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "SK") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "GR") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "SM") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "KS") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "CY") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "LT") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "ES") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "MC") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "NL") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "MF") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "LV") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "FR") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "AD") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "DE") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "ME") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "IE") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "AT") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "BE") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "FI") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "MT") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "SI") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "IT") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "EE") & (`curr' == "euro")
			replace `generate' = "EUR" if (`iso2c' == "PT") & (`curr' == "euro")
			replace `generate' = "FJD" if (`iso2c' == "FJ") & (`curr' == "fijian dollar")
			replace `generate' = "GBP" if (`iso2c' == "GB") & (`curr' == "pound sterling")
			replace `generate' = "GBP" if (`iso2c' == "IM") & (`curr' == "pound sterling")
			replace `generate' = "GBP" if (`iso2c' == "XI") & (`curr' == "pound sterling")
			replace `generate' = "GEL" if (`iso2c' == "GE") & (`curr' == "georgian lari")
			replace `generate' = "GHS" if (`iso2c' == "GH") & (`curr' == "new ghanaian cedi")
			replace `generate' = "GIP" if (`iso2c' == "GI") & (`curr' == "gibraltar pound")
			replace `generate' = "GMD" if (`iso2c' == "GM") & (`curr' == "gambian dalasi")
			replace `generate' = "GNF" if (`iso2c' == "GN") & (`curr' == "guinean franc")
			replace `generate' = "GTQ" if (`iso2c' == "GT") & (`curr' == "guatemalan quetzal")
			replace `generate' = "GYD" if (`iso2c' == "GY") & (`curr' == "guyana dollar")
			replace `generate' = "HKD" if (`iso2c' == "HK") & (`curr' == "hong kong dollar")
			replace `generate' = "HNL" if (`iso2c' == "HN") & (`curr' == "honduran lempira")
			replace `generate' = "HRK" if (`iso2c' == "HR") & (`curr' == "croatian kuna")
			replace `generate' = "HTG" if (`iso2c' == "HT") & (`curr' == "haitian gourde")
			replace `generate' = "HUF" if (`iso2c' == "HU") & (`curr' == "hungarian forint")
			replace `generate' = "IDR" if (`iso2c' == "ID") & (`curr' == "indonesian rupiah")
			replace `generate' = "ILS" if (`iso2c' == "PS") & (`curr' == "israeli new shekel")
			replace `generate' = "ILS" if (`iso2c' == "IL") & (`curr' == "israeli new shekel")
			replace `generate' = "INR" if (`iso2c' == "IN") & (`curr' == "indian rupee")
			replace `generate' = "IQD" if (`iso2c' == "IQ") & (`curr' == "iraqi dinar")
			replace `generate' = "IRR" if (`iso2c' == "IR") & (`curr' == "iranian rial")
			replace `generate' = "ISK" if (`iso2c' == "IS") & (`curr' == "iceland krona")
			replace `generate' = "JMD" if (`iso2c' == "JM") & (`curr' == "jamaican dollar")
			replace `generate' = "JOD" if (`iso2c' == "JO") & (`curr' == "jordanian dinar")
			replace `generate' = "JPY" if (`iso2c' == "JP") & (`curr' == "japanese yen")
			replace `generate' = "KES" if (`iso2c' == "KE") & (`curr' == "kenyan shilling")
			replace `generate' = "KGS" if (`iso2c' == "KG") & (`curr' == "kyrgyz som")
			replace `generate' = "KHR" if (`iso2c' == "KH") & (`curr' == "cambodian riel")
			replace `generate' = "KMF" if (`iso2c' == "KM") & (`curr' == "comorian franc")
			replace `generate' = "KPW" if (`iso2c' == "KP") & (`curr' == "democratic people's republic of korean won")
			replace `generate' = "KRW" if (`iso2c' == "KR") & (`curr' == "korean won")
			replace `generate' = "KWD" if (`iso2c' == "KW") & (`curr' == "kuwaiti dinar")
			replace `generate' = "KYD" if (`iso2c' == "KY") & (`curr' == "cayman islands dollar")
			replace `generate' = "KZT" if (`iso2c' == "KZ") & (`curr' == "kazakh tenge")
			replace `generate' = "LAK" if (`iso2c' == "LA") & (`curr' == "lao kip")
			replace `generate' = "LBP" if (`iso2c' == "LB") & (`curr' == "lebanese pound")
			replace `generate' = "LKR" if (`iso2c' == "LK") & (`curr' == "sri lankan rupee")
			replace `generate' = "LSL" if (`iso2c' == "LS") & (`curr' == "lesotho loti")
			replace `generate' = "LYD" if (`iso2c' == "LY") & (`curr' == "libyan dinar")
			replace `generate' = "MAD" if (`iso2c' == "MA") & (`curr' == "moroccan dirham")
			replace `generate' = "MDL" if (`iso2c' == "MD") & (`curr' == "moldovan leu")
			replace `generate' = "MGA" if (`iso2c' == "MG") & (`curr' == "malagasy ariary")
			replace `generate' = "MKD" if (`iso2c' == "MK") & (`curr' == "macedonian denar")
			replace `generate' = "MMK" if (`iso2c' == "MM") & (`curr' == "myanmar kyat")
			replace `generate' = "MNT" if (`iso2c' == "MN") & (`curr' == "mongolian tugrik")
			replace `generate' = "MOP" if (`iso2c' == "MO") & (`curr' == "macao pataca")
			replace `generate' = "MRO" if (`iso2c' == "MR") & (`curr' == "mauritanian ouguiya")
			replace `generate' = "MUR" if (`iso2c' == "MU") & (`curr' == "mauritian rupee")
			replace `generate' = "MVR" if (`iso2c' == "MV") & (`curr' == "maldivian rufiyaa")
			replace `generate' = "MWK" if (`iso2c' == "MW") & (`curr' == "malawi kwacha")
			replace `generate' = "MXN" if (`iso2c' == "MX") & (`curr' == "mexican peso")
			replace `generate' = "MYR" if (`iso2c' == "MY") & (`curr' == "malaysian ringgit")
			replace `generate' = "MZN" if (`iso2c' == "MZ") & (`curr' == "new mozambican metical")
			replace `generate' = "NAD" if (`iso2c' == "NA") & (`curr' == "namibian dollar")
			replace `generate' = "NGN" if (`iso2c' == "NG") & (`curr' == "nigerian naira")
			replace `generate' = "NIO" if (`iso2c' == "NI") & (`curr' == "nicaraguan gold cordoba")
			replace `generate' = "NOK" if (`iso2c' == "NO") & (`curr' == "norwegian krone")
			replace `generate' = "NPR" if (`iso2c' == "NP") & (`curr' == "nepalese rupee")
			replace `generate' = "NZD" if (`iso2c' == "NZ") & (`curr' == "new zealand dollar")
			replace `generate' = "OMR" if (`iso2c' == "OM") & (`curr' == "rial omani")
			replace `generate' = "OMR" if (`iso2c' == "OM") & (`curr' == "omani rial")
			replace `generate' = "PAB" if (`iso2c' == "PA") & (`curr' == "panamanian balboa")
			replace `generate' = "PEN" if (`iso2c' == "PE") & (`curr' == "peruvian new sol")
			replace `generate' = "PGK" if (`iso2c' == "PG") & (`curr' == "papua new guinea kina")
			replace `generate' = "PHP" if (`iso2c' == "PH") & (`curr' == "philippine peso")
			replace `generate' = "PKR" if (`iso2c' == "PK") & (`curr' == "pakistani rupee")
			replace `generate' = "PLN" if (`iso2c' == "PL") & (`curr' == "polish zloty")
			replace `generate' = "PYG" if (`iso2c' == "PY") & (`curr' == "paraguayan guarani")
			replace `generate' = "QAR" if (`iso2c' == "QA") & (`curr' == "qatari riyal")
			replace `generate' = "RON" if (`iso2c' == "RO") & (`curr' == "new romanian leu")
			replace `generate' = "RSD" if (`iso2c' == "RS") & (`curr' == "new serbian dinar")
			replace `generate' = "RUB" if (`iso2c' == "RU") & (`curr' == "russian ruble")
			replace `generate' = "RWF" if (`iso2c' == "RW") & (`curr' == "rwandan franc")
			replace `generate' = "SAR" if (`iso2c' == "SA") & (`curr' == "saudi arabian riyal")
			replace `generate' = "SBD" if (`iso2c' == "SB") & (`curr' == "solomon islands dollar")
			replace `generate' = "SCR" if (`iso2c' == "SC") & (`curr' == "seychelles rupee")
			replace `generate' = "SDG" if (`iso2c' == "SD") & (`curr' == "sudanese pound")
			replace `generate' = "SEK" if (`iso2c' == "SE") & (`curr' == "swedish krona")
			replace `generate' = "SGD" if (`iso2c' == "SG") & (`curr' == "singapore dollar")
			replace `generate' = "SLL" if (`iso2c' == "SL") & (`curr' == "sierra leonean leone")
			replace `generate' = "SOS" if (`iso2c' == "SO") & (`curr' == "somali shilling")
			replace `generate' = "SRD" if (`iso2c' == "SR") & (`curr' == "suriname dollar")
			replace `generate' = "SSP" if (`iso2c' == "SS") & (`curr' == "south sudanese pound")
			replace `generate' = "STN" if (`iso2c' == "ST") & (`curr' == "são tomé and principe dobra")
			replace `generate' = "SYP" if (`iso2c' == "SY") & (`curr' == "syrian pound")
			replace `generate' = "SZL" if (`iso2c' == "SZ") & (`curr' == "swaziland lilangeni")
			replace `generate' = "THB" if (`iso2c' == "TH") & (`curr' == "thai baht")
			replace `generate' = "TJS" if (`iso2c' == "TJ") & (`curr' == "tajik somoni")
			replace `generate' = "TMT" if (`iso2c' == "TM") & (`curr' == "turkmenistan manat")
			replace `generate' = "TND" if (`iso2c' == "TN") & (`curr' == "tunisian dinar")
			replace `generate' = "TOP" if (`iso2c' == "TO") & (`curr' == "tongan pa'anga")
			replace `generate' = "TRY" if (`iso2c' == "TR") & (`curr' == "new turkish lira")
			replace `generate' = "TTD" if (`iso2c' == "TT") & (`curr' == "trinidad and tobago dollar")
			replace `generate' = "TZS" if (`iso2c' == "TZ") & (`curr' == "tanzanian shilling")
			replace `generate' = "UAH" if (`iso2c' == "UA") & (`curr' == "ukrainian hryvnia")
			replace `generate' = "UGX" if (`iso2c' == "UG") & (`curr' == "ugandan shilling")
			replace `generate' = "USD" if (`iso2c' == "VI") & (`curr' == "u.s. dollar")
			replace `generate' = "USD" if (`iso2c' == "ZW") & (`curr' == "u.s. dollar")
			replace `generate' = "ZWD" if (`iso2c' == "ZW") & (`curr' == "zimbabwean dollar")
			replace `generate' = "USD" if (`iso2c' == "MP") & (`curr' == "u.s. dollar")
			replace `generate' = "USD" if (`iso2c' == "SV") & (`curr' == "u.s. dollar")
			replace `generate' = "USD" if (`iso2c' == "AS") & (`curr' == "u.s. dollar")
			replace `generate' = "USD" if (`iso2c' == "GU") & (`curr' == "u.s. dollar")
			replace `generate' = "USD" if (`iso2c' == "PW") & (`curr' == "u.s. dollar")
			replace `generate' = "USD" if (`iso2c' == "FM") & (`curr' == "u.s. dollar")
			replace `generate' = "USD" if (`iso2c' == "MH") & (`curr' == "u.s. dollar")
			replace `generate' = "USD" if (`iso2c' == "US") & (`curr' == "u.s. dollar")
			replace `generate' = "USD" if (`iso2c' == "LR") & (`curr' == "u.s. dollar")
			replace `generate' = "USD" if (`iso2c' == "PR") & (`curr' == "u.s. dollar")
			replace `generate' = "USD" if (`iso2c' == "VG") & (`curr' == "u. s. dollar")
			replace `generate' = "USD" if (`iso2c' == "TL") & (`curr' == "u.s. dollar")
			replace `generate' = "USD" if (`iso2c' == "TC") & (`curr' == "u.s. dollar")
			replace `generate' = "USD" if (`iso2c' == "EC") & (`curr' == "u.s. dollar")
			replace `generate' = "USD" if (`iso2c' == "VG") & (`curr' == "u.s. dollar")
			replace `generate' = "UYU" if (`iso2c' == "UY") & (`curr' == "uruguayan peso")
			replace `generate' = "UZS" if (`iso2c' == "UZ") & (`curr' == "uzbek sum")
			replace `generate' = "UZS" if (`iso2c' == "UZ") & (`curr' == "uzbek som")
			replace `generate' = "VEF" if (`iso2c' == "VE") & (`curr' == "venezuelan bolivar fuerte")
			replace `generate' = "VES" if (`iso2c' == "VE") & (`curr' == "bolivar digital")			
			replace `generate' = "VND" if (`iso2c' == "VN") & (`curr' == "dong")
			replace `generate' = "VND" if (`iso2c' == "VN") & (`curr' == "vietnamese dong")
			replace `generate' = "VUV" if (`iso2c' == "VU") & (`curr' == "vanuatu vatu")
			replace `generate' = "WST" if (`iso2c' == "WS") & (`curr' == "samoan tala")
			replace `generate' = "XAF" if (`iso2c' == "GA") & (`curr' == "central african cfa franc")
			replace `generate' = "XAF" if (`iso2c' == "TD") & (`curr' == "central african cfa franc")
			replace `generate' = "XAF" if (`iso2c' == "CG") & (`curr' == "central african cfa franc")
			replace `generate' = "XAF" if (`iso2c' == "GQ") & (`curr' == "central african cfa franc")
			replace `generate' = "XAF" if (`iso2c' == "CM") & (`curr' == "central african cfa franc")
			replace `generate' = "XAF" if (`iso2c' == "CF") & (`curr' == "central african cfa franc")
			replace `generate' = "XCD" if (`iso2c' == "VC") & (`curr' == "east caribbean dollar")
			replace `generate' = "XCD" if (`iso2c' == "AG") & (`curr' == "east caribbean dollar")
			replace `generate' = "XCD" if (`iso2c' == "GD") & (`curr' == "east caribbean dollar")
			replace `generate' = "XCD" if (`iso2c' == "KN") & (`curr' == "east caribbean dollar")
			replace `generate' = "XCD" if (`iso2c' == "LC") & (`curr' == "east caribbean dollar")
			replace `generate' = "XCD" if (`iso2c' == "DM") & (`curr' == "east caribbean dollar")
			replace `generate' = "XOF" if (`iso2c' == "GW") & (`curr' == "west african cfa franc")
			replace `generate' = "XOF" if (`iso2c' == "SN") & (`curr' == "west african cfa franc")
			replace `generate' = "XOF" if (`iso2c' == "ML") & (`curr' == "west african cfa franc")
			replace `generate' = "XOF" if (`iso2c' == "NE") & (`curr' == "west african cfa franc")
			replace `generate' = "XOF" if (`iso2c' == "BJ") & (`curr' == "west african cfa franc")
			replace `generate' = "XOF" if (`iso2c' == "BF") & (`curr' == "west african cfa franc")
			replace `generate' = "XOF" if (`iso2c' == "CI") & (`curr' == "west african cfa franc")
			replace `generate' = "XOF" if (`iso2c' == "TG") & (`curr' == "west african cfa franc")
			replace `generate' = "XPF" if (`iso2c' == "PF") & (`curr' == "cfp franc")
			replace `generate' = "XPF" if (`iso2c' == "NC") & (`curr' == "cfp franc")
			replace `generate' = "YER" if (`iso2c' == "YE") & (`curr' == "yemeni rial")
			replace `generate' = "ZAR" if (`iso2c' == "ZA") & (`curr' == "south african rand")
			replace `generate' = "ZMW" if (`iso2c' == "ZM") & (`curr' == "new zambian kwacha")
		}
		else {
			display as error "option 'from' incorrectly specified"
			exit 198
		}
	}
	
	// Check that we did not forget any country
	assert `generate' != ""
end
