
// This file imports OECD NFI data as a share of GDP for using them in the construction of NFI series in the database

cd "C:\Users\Amory\Documents\GitHub\wid-world\data-input\oecd-data\nfi"

import delimited "SNA_TABLE2_04072018110921116.csv", varn(1) clear

keep if strpos(transaction,"Net primary incomes")>0 | strpos(transaction,"Gross domestic product")>0
keep ïlocation country year unitcode transaction value
renvars ïlocation unitcode / iso3 currency 
kountry iso3, from(iso3c) to(iso2c)
ren _ISO2C_ iso

gen dum=1 if strpos(transaction,"Net primary incomes")>0
replace dum=2 if strpos(transaction,"Gross domestic product")>0
drop transaction
reshape wide value, i(country year) j(dum)
renvars value1 value2 / nfi_lcu_oecd gdp_lcu_oecd
gen nfi_pct_oecd=nfi_lcu_oecd/gdp_lcu_oecd

drop if mi(iso) // drop Western Germany and EU
drop country iso3
drop currency
order iso year

label data "Generated by import-oecd-nfi.do, in data-input/oecd-data/nfi"
save "oecd-nfi.dta", replace


